Bug fix in panel PEL code
ibm-openbmc/ibm-panel pull request #150
Opened 2022-07-13 15:01 UTC by PriyangaRamasamy

This commit fixes invalid CALLOUT_I2C_ADDR format
printed in Transport class PEL code.

This commit also has few other minor fixes in the
Transport class code.

Test:
Tested that the CALLOUT_I2C_ADDR is getting printed in
right format(hex format).

peltool -i 0x50000532
{
"Private Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x5000",
    "Created at":               "07/12/2022 18:59:54",
    "Committed at":             "07/12/2022 18:59:54",
    "Creator Subsystem":        "BMC",
    "CSSVER":                   "",
    "Platform Log Id":          "0x50000532",
    "Entry Id":                 "0x50000532",
    "BMC Event Log Id":         "4"
},
"User Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Log Committed by":         "0x2000",
    "Subsystem":                "CEC Hardware - Operator Panel",
    "Event Scope":              "Entire Platform",
    "Event Severity":           "Predictive Error",
    "Event Type":               "Not Applicable",
    "Action Flags": [
                                "Service Action Required",
                                "Report Externally",
                                "HMC Call Home"
    ],
    "Host Transmission":        "Not Sent",
    "HMC Transmission":         "Not Sent"
},
"Primary SRC": {
    "Section Version":          "1",
    "Sub-section type":         "1",
    "Created by":               "0x5000",
    "SRC Version":              "0x02",
    "SRC Format":               "0x55",
    "Virtual Progress SRC":     "False",
    "I5/OS Service Event Bit":  "False",
    "Hypervisor Dump Initiated":"False",
    "Backplane CCIN":           "2E43",
    "Terminate FW Error":       "False",
    "Deconfigured":             "False",
    "Guarded":                  "False",
    "Error Details": {
        "Message":              "Unable to open device path or ioctl failure"
    },
    "Valid Word Count":         "0x09",
    "Reference Code":           "BD595002",
    "Hex Word 2":               "00080055",
    "Hex Word 3":               "2E430010",
    "Hex Word 4":               "00000000",
    "Hex Word 5":               "00000000",
    "Hex Word 6":               "00000000",
    "Hex Word 7":               "00000000",
    "Hex Word 8":               "00000000",
    "Hex Word 9":               "00000000"
},
"Extended User Header": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x2000",
    "Reporting Machine Type":   "9105-42A",
    "Reporting Serial Number":  "13BE990",
    "FW Released Ver":          "",
    "FW SubSys Version":        "fw1020.00-61",
    "Common Ref Time":          "00/00/0000 00:00:00",
    "Symptom Id Len":           "20",
    "Symptom Id":               "BD595002_2E430010"
},
"Failing MTMS": {
    "Section Version":          "1",
    "Sub-section type":         "0",
    "Created by":               "0x2000",
    "Machine Type Model":       "9105-42A",
    "Serial Number":            "13BE990"
},
"User Data 0": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "BMCState": "Ready",
    "BootState": "Unspecified",
    "ChassisState": "Off",
    "FW Version ID": "fw1020.00-61-50-g36a53df782-dirty",
    "HostState": "Off",
    "System IM": "50001000"
},
"User Data 1": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "CALLOUT_ERRNO": "2",
    "CALLOUT_IIC_ADDR": "0x5A",
    "CALLOUT_IIC_BUS": "/abc",
    "DESCRIPTION": "Failed to open device file. Errno : 2Errno description : No such file or directory for device path /abc"
},
"User Data 2": {
    "Section Version": "1",
    "Sub-section type": "1",
    "Created by": "0x2000",
    "PEL Internal Debug Data": {
        "SRC": [
            "Invalid CALLOUT_IIC_BUS /abc or CALLOUT_IIC_ADDR 0x5A in AdditionalData property"
        ]
    }
}
}

Change-Id: Iac30c70d1c31669411d6daf0091b339ffc938292
Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>

2022-07-13 15:08 UTC, PriyangaRamasamy commented
Fixes SW554180

2022-07-20 05:00 UTC, jinuthomas requested changes
I guess this is approved for 1020.10 , so please move the PR to 1020.10 branch

2022-07-20 07:55 UTC, jinuthomas approved these changes

2022-07-20 10:38 UTC, jinuthomas requested changes
does the button_handler.cpp code also need "CALLOUT_ERRNO"

2022-07-21 06:13 UTC, jinuthomas approved these changes

2022-07-21 06:14 UTC, merged