directory structure for logger library
ibm-openbmc/ibm-panel pull request #200
Opened 2023-09-21 08:38 UTC by RekhaAparna01

Initial Directory structure for logger library

This commit marks the initial creation of the logger library. 
The library is set up with the following directory structure:
1. 'includes/' directory: contains the header files of the library
2. 'src/' directory: Contains the source code of the library.
3. 'tests/' directory: test files to ensure the library's functionality.

The library is currently in its early stages
subsequent commits will introduce code, features, and documentation.

Change-Id: I21981ef21b668beee315ad2899c56c71fbd86859

2023-09-21 09:54 UTC, SunnySrivastava1984 requested changes
The commit message should follow a specific format as given in the link.
https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

Also, in commit message try to define purpose of the commit, as to what is done in the commit.

2023-09-21 15:00 UTC, GiridhariKrishna commented
Can we have use cases too for these structures. Thanks.

2023-09-22 11:28 UTC, SunnySrivastava1984 approved these changes

2023-09-22 18:11 UTC, GiridhariKrishnan approved these changes

2023-09-25 05:33 UTC, jinuthomas approved these changes

2023-09-25 05:33 UTC, merged