ExecuteFunction dbus method throws exception
ibm-openbmc/ibm-panel pull request #204
Opened 2023-10-17 04:47 UTC by PriyangaRamasamy

Change-Id: I3d72e0f0a4ee3b6b199febbdc0efc33c8b9e6546

2023-10-17 18:00 UTC, PriyangaRamasamy commented
jenkins run tests please

2023-10-18 04:59 UTC, SunnySrivastava1984 requested changes

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on include/panel_state_manager.hpp
> +     * @brief API which tells if the function is supported to execute from
Limit brief to one line.

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/utils.cpp
> +    std::cout << "L1 : " << line1 << std::endl;
Comment these back?

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/panel_state_manager.cpp
> +using NotAllowed = sdbusplus::xyz::openbmc_project::Common::Error::NotAllowed;
Use in-place. Lets move away from mistakes we did in past :)

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/executor.cpp
> +    catch (const sdbusplus::exception_t& e)
Isn't this derived from std::exception? If so it can be caught there as well.
When the code is same in both the cases, base catch is sufficient.

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/executor.cpp
> +using InternalFailure =
Can be used in place or at-least keep the scope minimal.

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/executor.cpp
> +        std::cerr << e.what() << std::endl;
Along with e.what(), add the details that you had in the cerr previously. Will be helpful in debugging.

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/panel_state_manager.cpp
> +    std::vector<types::FunctionNumber> supportedFuncs = {21, 22, 34, 65, 66,
We have a type defined for this "FunctionalityList". Please use that for better readability.

2023-10-18 04:59 UTC, SunnySrivastava1984 commented on src/panel_state_manager.cpp
> +    auto pos = find(supportedFuncs.begin(), supportedFuncs.end(), funcNum);
Can get rid of an extra variable as knowing position in this case is not required for any processing further.
if(find(supportedFuncs.begin(), supportedFuncs.end(), funcNum) != supportedFuncs.end()) ?

2023-10-18 12:35 UTC, SunnySrivastava1984 approved these changes

2023-10-19 04:47 UTC, merged