Update condition get enabled GUI functions
ibm-openbmc/ibm-panel pull request #208
Opened 2024-03-16 05:14 UTC by SunnySrivastava1984

Codition to get the list of enabled GUI function has been fixed.

Test:
root@a902be:~# busctl call com.ibm.PanelApp /com/ibm/panel_app com.ibm.panel toggleFunctionState ay 9 0 0 96 0 0 2 0 0 66

Mar 16 05:02:13 a902be ibm-panel[6442]:
Bitmap received: 00 00 60 00 00 02 00 00 42
Mar 16 05:02:13 a902be ibm-panel[6442]:  Function enabled: 15 Mar 16 05:02:13 a902be ibm-panel[6442]:  Function enabled: 16 Mar 16 05:02:13 a902be ibm-panel[6442]:  Function enabled: 29 Mar 16 05:02:13 a902be ibm-panel[6442]:  Function enabled: 41 Mar 16 05:02:13 a902be ibm-panel[6442]:  Function enabled: 46

busctl call com.ibm.PanelApp /com/ibm/panel_app com.ibm.panel getEnabledFunctions ay 4 21 22 65 70

Note: Numbers in the logs against function enabled are in hex, corresponding decimal number functions are enabled as shown in the function call to getEnabledFunctions.
Function 41 is not returned as it is not in the list of functions which can be accessed via GUI.

2024-03-16 12:50 UTC, jinuthomas requested changes
nit : Condition [in commit message]

2024-03-16 12:50 UTC, jinuthomas commented on src/panel_state_manager.cpp
> +        // if the function is enabled by Phyp and system at Phyp runtime.
nit: PHYP

2024-03-16 16:09 UTC, SunnySrivastava1984 commented on src/panel_state_manager.cpp
> +        // if the function is enabled by Phyp and system at Phyp runtime.
Done.

2024-03-16 16:10 UTC, SunnySrivastava1984 commented
> nit : Condition [in commit message]

Done

2024-03-18 03:26 UTC, jinuthomas approved these changes

2024-03-18 03:26 UTC, merged