Move to libpldm APIs for Allocating Instance IDs and change Transport APIs
ibm-openbmc/ibm-panel pull request #213
Opened 2024-07-10 21:32 UTC by Lakshmi-y

Replace the current APIs with libpldm APIs for allocating instance IDs directly.  This eliminates the need for remote D-Bus calls to the pldm daemon.

Replace pldm transport APIs with libpldm pldm_transport APIs. This change migrates the application off the deprecated "requester" APIs in libpldm. Since we currently lack the infrastructure to obtain the correct TIDs, use the EID as the TID in the EID-to-TID mapping to maintain the current functionality.

Change-Id: I5854aa022582ceae6a1843983fc90181b7e6d55f

2024-07-11 03:03 UTC, Lakshmi-y commented
I created one commit for both instance ID API and transport API changes.
Changes are similar to phosphor-debug-collector, waiting for review,
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/72594
https://gerrit.openbmc.org/c/openbmc/phosphor-debug-collector/+/72595

2024-07-11 03:05 UTC, Lakshmi-y commented
Journalctl out:
ul 09 20:07:33 rain104bmc ibm-panel[1545]: Button event 2 At function - 16 Panel cur state = 2e
Jul 09 20:09:09 rain104bmc ibm-panel[1545]: Sub function executed = 0
Jul 09 20:09:09 rain104bmc ibm-panel[1545]: Got instanceId: 0 from PLDM eid: 9
Jul 09 20:09:09 rain104bmc ibm-panel[1545]: packet data sent to pldm: 80 02 39 08 00 01 01 16
Jul 09 20:09:09 rain104bmc ibm-panel[1545]: Button event 2 At function - 16 Panel cur state = 2e
Jul 09 20:09:09 rain104bmc pldmd[2132]: Got a repo change event from TID: 208
Jul 09 20:09:09 rain104bmc pldmd[2132]: pldmPDRRepositoryChgEvent eventDataOperation : 3
Jul 09 20:09:09 rain104bmc pldmd[2132]: Record handles sent down to BMC: 33554449
Jul 09 20:09:10 rain104bmc pldmd[2132]: Panel:BitMap received: 00 00 00 
Jul 09 20:09:10 rain104bmc ibm-panel[1545]: Bitmap received: 00 00 00
Jul 09 20:09:10 rain104bmc ibm-panel[1545]: Empty function list received. Functions enabled before will be disabled.
Jul 09 20:09:10 rain104bmc ibm-panel[1545]:  Function Disabled: 16
Jul 09 20:09:10 rain104bmc ibm-panel[1545]: Button event 2 At function - 16 Panel cur state = 2e
Jul 09 20:09:12 rain104bmc ibm-panel[1545]: Sub function executed = 0
Jul 09 20:09:12 rain104bmc ibm-panel[1545]: Got instanceId: 0 from PLDM eid: 9
Jul 09 20:09:12 rain104bmc ibm-panel[1545]: packet data sent to pldm: 80 02 39 08 00 01 01 16
Jul 09 20:09:12 rain104bmc ibm-panel[1545]: Button event 2 At function - 16 Panel cur state = 2e
Jul 09 20:10:04 rain104bmc pldmd[2132]: 81 02 0a 01 01 00 15 00 01 00 02 00
Jul 09 20:10:04 rain104bmc pldmd[2132]: 81 02 0a 01 01 00 15 00 01 00 02 00
Jul 09 20:10:05 rain104bmc pldmd[2132]: Got a repo change event from TID: 208
Jul 09 20:10:05 rain104bmc pldmd[2132]: pldmPDRRepositoryChgEvent eventDataOperation : 3
Jul 09 20:10:05 rain104bmc pldmd[2132]: Record handles sent down to BMC: 33554449
Jul 09 20:10:05 rain104bmc pldmd[2132]: Panel:BitMap received: 00 00 40 
Jul 09 20:10:08 rain104bmc ibm-panel[1545]: Bitmap received: 00 00 40
Jul 09 20:10:08 rain104bmc ibm-panel[1545]:  Function enabled: 16

2024-07-19 05:03 UTC, SunnySrivastava1984 requested changes

2024-07-19 05:06 UTC, SunnySrivastava1984 requested changes
I could not understand from the commit message why this change was required.
Could you please add that to the commit message so that I can get some context w.r.t. the changes.

2024-07-19 05:09 UTC, SunnySrivastava1984 requested changes

2024-07-19 05:09 UTC, SunnySrivastava1984 commented on meson_options.txt
> +option(
So, which one needs to be used and based on what criteria is it decided?

2024-08-30 03:38 UTC, jinuthomas requested changes
I see that there is a lot of if...else , which I am not a fan of , why do we need two types of mctp in this repo? 
All I do have concerns on the exception handling , as it is not per pour coding standards.
Could you retry this code.

2025-07-30 04:13 UTC, closed without merging